cc_binary(
    name = "viewer",
    srcs = [
            "main.cc",
           ],
    deps = [
            "//library/kitti",
            "//library/osg_nodes",
            "//library/timer",
            "//library/viewer",
            "@openscenegraph//:openscenegraph",
           ],
)
