cc_binary(
    name = "viewer",
    srcs = glob(["*.cc", "*.h"]),
    deps = [
            "//library/kitti",
            "//library/osg_nodes",
            "//library/timer",
            "//library/viewer",
            "@openscenegraph//:openscenegraph",
           ],
)
