cc_binary(
    name = "kitti_occ_grids",
    srcs = [
            "main.cc",
            "occ_grid_extractor.cc", "occ_grid_extractor.h",
           ],
    deps = [
            "//library/kitti",
            "//library/ray_tracing",
            "//library/timer",
           ],
)
