new_local_repository(
    name = "eigen",
    path = "/usr/include/eigen3",
    build_file = "tools/eigen.BUILD"
)

new_local_repository(
    name = "cuda",
    build_file = "tools/cuda.BUILD",
    path = "/usr/local/cuda-8.0/"
)
