cc_binary(
    name = "test",
    srcs = ["test.cc"],
    deps = [
            "//library/detection_mapping",
            "//library/kitti",
            "//library/timer",
            "//library/osg_nodes",
            "//library/viewer",
           ],
)
