cc_binary(
    name = "bayesian_inference",
    srcs = glob(["*.cc", "*.h"]),
    linkopts = ["-lm"],
    deps = [
            "@eigen//:eigen",
            "//library/bayesian_inference",
           ],
)
